/*
 * DIO_configuration.h
 *
 *  Created on: Aug 3, 2022
 *      Author: abdelrahmanhossam
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CONFIGURATION_H_
#define INCLUDE_MCAL_DIO_DIO_CONFIGURATION_H_

// Direction :- PIN_INPUT , PIN_OUTPUT

#define PORTA_PIN0_DIRECTION PIN_OUTPUT
#define PORTA_PIN1_DIRECTION PIN_OUTPUT
#define PORTA_PIN2_DIRECTION PIN_OUTPUT
#define PORTA_PIN3_DIRECTION PIN_OUTPUT
#define PORTA_PIN4_DIRECTION PIN_OUTPUT
#define PORTA_PIN5_DIRECTION PIN_OUTPUT
#define PORTA_PIN6_DIRECTION PIN_OUTPUT
#define PORTA_PIN7_DIRECTION PIN_OUTPUT

#define PORTB_PIN0_DIRECTION PIN_OUTPUT
#define PORTB_PIN1_DIRECTION PIN_OUTPUT
#define PORTB_PIN2_DIRECTION PIN_OUTPUT
#define PORTB_PIN3_DIRECTION PIN_OUTPUT
#define PORTB_PIN4_DIRECTION PIN_INPUT
#define PORTB_PIN5_DIRECTION PIN_INPUT
#define PORTB_PIN6_DIRECTION PIN_OUTPUT
#define PORTB_PIN7_DIRECTION PIN_INPUT

#define PORTC_PIN0_DIRECTION PIN_OUTPUT
#define PORTC_PIN1_DIRECTION PIN_OUTPUT
#define PORTC_PIN2_DIRECTION PIN_OUTPUT
#define PORTC_PIN3_DIRECTION PIN_OUTPUT
#define PORTC_PIN4_DIRECTION PIN_OUTPUT
#define PORTC_PIN5_DIRECTION PIN_OUTPUT
#define PORTC_PIN6_DIRECTION PIN_OUTPUT
#define PORTC_PIN7_DIRECTION PIN_OUTPUT

#define PORTD_PIN0_DIRECTION PIN_OUTPUT
#define PORTD_PIN1_DIRECTION PIN_OUTPUT
#define PORTD_PIN2_DIRECTION PIN_OUTPUT
#define PORTD_PIN3_DIRECTION PIN_OUTPUT
#define PORTD_PIN4_DIRECTION PIN_OUTPUT
#define PORTD_PIN5_DIRECTION PIN_OUTPUT
#define PORTD_PIN6_DIRECTION PIN_OUTPUT
#define PORTD_PIN7_DIRECTION PIN_OUTPUT

// Value:-
//          OUTPUT :- PIN_LOW - PIN_HIGH
//          INPUT  :- PIN_PULLUP - PIN_FLOATING
#define PORTA_PIN0_VALUE PIN_HIGH
#define PORTA_PIN1_VALUE PIN_LOW
#define PORTA_PIN2_VALUE PIN_LOW
#define PORTA_PIN3_VALUE PIN_LOW
#define PORTA_PIN4_VALUE PIN_LOW
#define PORTA_PIN5_VALUE PIN_LOW
#define PORTA_PIN6_VALUE PIN_LOW
#define PORTA_PIN7_VALUE PIN_LOW

#define PORTB_PIN0_VALUE PIN_LOW
#define PORTB_PIN1_VALUE PIN_LOW
#define PORTB_PIN2_VALUE PIN_LOW
#define PORTB_PIN3_VALUE PIN_LOW
#define PORTB_PIN4_VALUE PIN_PULLUP // vcc
#define PORTB_PIN5_VALUE PIN_PULLUP
#define PORTB_PIN6_VALUE PIN_HIGH // MISO
#define PORTB_PIN7_VALUE PIN_PULLUP

#define PORTC_PIN0_VALUE PIN_LOW
#define PORTC_PIN1_VALUE PIN_LOW
#define PORTC_PIN2_VALUE PIN_LOW
#define PORTC_PIN3_VALUE PIN_LOW
#define PORTC_PIN4_VALUE PIN_LOW
#define PORTC_PIN5_VALUE PIN_LOW
#define PORTC_PIN6_VALUE PIN_LOW
#define PORTC_PIN7_VALUE PIN_LOW

#define PORTD_PIN0_VALUE PIN_LOW
#define PORTD_PIN1_VALUE PIN_LOW
#define PORTD_PIN2_VALUE PIN_HIGH
#define PORTD_PIN3_VALUE PIN_HIGH
#define PORTD_PIN4_VALUE PIN_LOW
#define PORTD_PIN5_VALUE PIN_LOW
#define PORTD_PIN6_VALUE PIN_LOW
#define PORTD_PIN7_VALUE PIN_LOW
#endif /* INCLUDE_MCAL_DIO_DIO_CONFIGURATION_H_ */
